import "../styles/globals.css"
import ResponsiveAppBar from "./ResponsiveAppBar"

export const metadata = {
  title: 'FrontEnd',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  )
}
